//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeanIO.Internal.Parser.Format.Xml {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeanIO.Internal.Parser.Format.Xml.DefaultMessages", typeof(DefaultMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid padded field length, expected {4} characters ähnelt.
        /// </summary>
        internal static string fielderror_length {
            get {
                return ResourceManager.GetString("fielderror.length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected literal value &apos;{4}&apos; ähnelt.
        /// </summary>
        internal static string fielderror_literal {
            get {
                return ResourceManager.GetString("fielderror.literal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum field length is {5} characters ähnelt.
        /// </summary>
        internal static string fielderror_maxLength {
            get {
                return ResourceManager.GetString("fielderror.maxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected maximum {5} occurrences ähnelt.
        /// </summary>
        internal static string fielderror_maxOccurs {
            get {
                return ResourceManager.GetString("fielderror.maxOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum field length is {4} characters ähnelt.
        /// </summary>
        internal static string fielderror_minLength {
            get {
                return ResourceManager.GetString("fielderror.minLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected minimum {4} occurrences ähnelt.
        /// </summary>
        internal static string fielderror_minOccurs {
            get {
                return ResourceManager.GetString("fielderror.minOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Field is not nullable ähnelt.
        /// </summary>
        internal static string fielderror_nillable {
            get {
                return ResourceManager.GetString("fielderror.nillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unmatched regular expression &apos;{4}&apos; ähnelt.
        /// </summary>
        internal static string fielderror_regex {
            get {
                return ResourceManager.GetString("fielderror.regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required field not set ähnelt.
        /// </summary>
        internal static string fielderror_required {
            get {
                return ResourceManager.GetString("fielderror.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type conversion error: {4} ähnelt.
        /// </summary>
        internal static string fielderror_type {
            get {
                return ResourceManager.GetString("fielderror.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Malformed record at line {0}: {3} ähnelt.
        /// </summary>
        internal static string recorderror_malformed {
            get {
                return ResourceManager.GetString("recorderror.malformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected {1} record at line {0} ähnelt.
        /// </summary>
        internal static string recorderror_unexpected {
            get {
                return ResourceManager.GetString("recorderror.unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unidentified record at line {0} ähnelt.
        /// </summary>
        internal static string recorderror_unidentified {
            get {
                return ResourceManager.GetString("recorderror.unidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expected record/group {1} at line {0} ähnelt.
        /// </summary>
        internal static string recorderror_unsatisfied {
            get {
                return ResourceManager.GetString("recorderror.unsatisfied", resourceCulture);
            }
        }
    }
}
